[package]
name = "metrics"
version = "0.1.0"
authors = ["David Wong <davidwg@calibra.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38" # error handling library
guppy = "0.6.3" # library to analyze deps
git2 = "0.13.15" # git library
guppy-summaries = "0.3.1" # guppy summaries 
mongodb = "1.1.1" # database used to store result of cronjobs
semver = "0.11.0" # semver of dependencies
serde = { version = "1.0", features = ["derive"] } # bson serialization
serde_json = "1.0" # bson serialization
tempfile = "3.2.0" # temporary folder helper
tokio = { version = "0.2.18", features = ["full"] } # old version because of mongodb driver...

# helper to populate database with test data
[[bin]]
name = "populate_test_data"
# test = false # needed?
