on: [push, pull_request]
name: Clippy
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets --manifest-path=./web-backend/Cargo.toml -- -W clippy:integer_arithmetic -W clippy::indexing_slicing -W clippy::panic_in_result_function -W clippy::unwrap_in_result -W clippy::as_conversions -W clippy::checked_conversions
      - uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets --manifest-path=./web-backend/metrics/Cargo.toml -- -W clippy:integer_arithmetic -W clippy::indexing_slicing -W clippy::panic_in_result_function -W clippy::unwrap_in_result -W clippy::as_conversions -W clippy::checked_conversions
